networks:
  phi_network:
    ipam:
      driver: default
      config:
        - subnet: 10.1.0.0/24

services:
  monitor1:
    build:
      context: ./..
      dockerfile: Dockerfile
    volumes:
      - type: tmpfs
        target: /data/
    environment:
      RAFT_BIND: "10.1.0.111:7000"
      HTTP_BIND: "10.1.0.111:8000"
      IDENTIFIER: "node_1"
      HTTP: "True"
      BOOTSTRAP: "True"
    ports:
      - "8000:8000"
      - "7000:7000"
    networks:
      phi_network:
        ipv4_address: '10.1.0.111'
    depends_on:
      - server1
      - server2
      - server3
      - server4
      - server5
      - server6
      - server7
      - server8
      - server9
      - server10
    command: sh -c "/app/phi --config ./servers.yml"
  monitor2:
    build:
      context: ./..
      dockerfile: Dockerfile
    volumes:
      - type: tmpfs
        target: /data/
    environment:
      RAFT_BIND: "10.1.0.112:7000"
      HTTP_BIND: "10.1.0.112:8000"
      JOIN: "10.1.0.111:8000" 
      IDENTIFIER: "node_2"
      HTTP: "True"
    ports:
      - "8001:8000"
      - "7001:7000"
    networks:
      phi_network:
        ipv4_address: '10.1.0.112'
    depends_on:
      - monitor1
    command: sh -c "/app/phi"
  monitor3:
    build:
      context: ./..
      dockerfile: Dockerfile
    volumes:
      - type: tmpfs
        target: /data/
    environment:
      RAFT_BIND: "10.1.0.113:7000"
      HTTP_BIND: "10.1.0.113:8000"
      JOIN: "10.1.0.111:8000"
      IDENTIFIER: "node_3"
      HTTP: "True"
    ports:
      - "8002:8000"
      - "7002:7000"
    networks:
      phi_network:
        ipv4_address: '10.1.0.113'
    depends_on:
      - monitor1
    command: sh -c "/app/phi"
  monitor4:
    build:
      context: ./..
      dockerfile: Dockerfile
    volumes:
      - type: tmpfs
        target: /data/
    environment:
      RAFT_BIND: "10.1.0.114:7000"
      HTTP_BIND: "10.1.0.114:8000"
      JOIN: "10.1.0.111:8000"
      IDENTIFIER: "node_4"
      HTTP: "True"
    ports:
      - "8003:8000"
      - "7003:7000"
    networks:
      phi_network:
        ipv4_address: '10.1.0.114'
    depends_on:
      - monitor1
    command: sh -c "/app/phi"

  server1:
    build: .
    command: python server.py
    volumes:
      - type: tmpfs
        target: /data/
    networks:
      phi_network:
        ipv4_address: '10.1.0.101'
    ports:
      - "8081:8080"
    logging:
      driver: "none"

  server2:
    build: .
    command: python server.py
    volumes:
      - type: tmpfs
        target: /data/
    networks:
      phi_network:
        ipv4_address: '10.1.0.102'
    ports:
      - "8082:8080"
    logging:
      driver: "none"

  server3:
    build: .
    command: python server.py
    volumes:
      - type: tmpfs
        target: /data/
    networks:
      phi_network:
        ipv4_address: '10.1.0.103'
    ports:
      - "8083:8080"
    logging:
      driver: "none"

  server4:
    build: .
    command: python server.py
    volumes:
      - type: tmpfs
        target: /data/
    networks:
      phi_network:
        ipv4_address: '10.1.0.104'
    ports:
      - "8084:8080"
    logging:
      driver: "none"

  server5:
    build: .
    command: python server.py
    volumes:
      - type: tmpfs
        target: /data/
    networks:
      phi_network:
        ipv4_address: '10.1.0.105'
    ports:
      - "8085:8080"
    logging:
      driver: "none"



  server6:
    build: .
    command: python server.py
    volumes:
      - type: tmpfs
        target: /data/
    networks:
      phi_network:
        ipv4_address: '10.1.0.106'
    ports:
      - "8086:8080"
    logging:
      driver: "none"

  server7:
    build: .
    command: python server.py
    volumes:
      - type: tmpfs
        target: /data/
    networks:
      phi_network:
        ipv4_address: '10.1.0.107'
    ports:
      - "8087:8080"
    logging:
      driver: "none"

  server8:
    build: .
    command: python server.py
    volumes:
      - type: tmpfs
        target: /data/
    networks:
      phi_network:
        ipv4_address: '10.1.0.108'
    ports:
      - "8088:8080"
    logging:
      driver: "none"

  server9:
    build: .
    command: python server.py
    volumes:
      - type: tmpfs
        target: /data/
    networks:
      phi_network:
        ipv4_address: '10.1.0.109'
    ports:
      - "8089:8080"
    logging:
      driver: "none"

  server10:
    build: .
    command: python server.py
    volumes:
      - type: tmpfs
        target: /data/
    networks:
      phi_network:
        ipv4_address: '10.1.0.110'
    ports:
      - "8090:8080"
    logging:
      driver: "none"
